### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [1]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([18, 86, 27, 73, 61, 40, 21, 36, 84, 43, 58,  3, 94, 52, 47],
      dtype=int32)

In [2]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[39, 73, 62, 66],
       [47, 58, 83, 62],
       [94, 77, 34, 69],
       [54, 36,  2, 95],
       [68,  9, 55, 80],
       [55, 14, 17, 96]], dtype=int32)

In [4]:

np.sort(a)[::-1]

array([94, 86, 84, 73, 61, 58, 52, 47, 43, 40, 36, 27, 21, 18,  3],
      dtype=int32)

In [6]:
b

array([[39, 73, 62, 66],
       [47, 58, 83, 62],
       [94, 77, 34, 69],
       [54, 36,  2, 95],
       [68,  9, 55, 80],
       [55, 14, 17, 96]], dtype=int32)

In [9]:
np.sort(b,axis=1)
#0=col 1=row

array([[39, 62, 66, 73],
       [47, 58, 62, 83],
       [34, 69, 77, 94],
       [ 2, 36, 54, 95],
       [ 9, 55, 68, 80],
       [14, 17, 55, 96]], dtype=int32)

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [10]:
# code
np.append(a,200)

array([ 18,  86,  27,  73,  61,  40,  21,  36,  84,  43,  58,   3,  94,
        52,  47, 200])

In [12]:
b

array([[39, 73, 62, 66],
       [47, 58, 83, 62],
       [94, 77, 34, 69],
       [54, 36,  2, 95],
       [68,  9, 55, 80],
       [55, 14, 17, 96]], dtype=int32)

In [20]:
c=[[1,2,3,4]]

In [21]:
np.append(b,c,axis=0)

array([[39, 73, 62, 66],
       [47, 58, 83, 62],
       [94, 77, 34, 69],
       [54, 36,  2, 95],
       [68,  9, 55, 80],
       [55, 14, 17, 96],
       [ 1,  2,  3,  4]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [22]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [24]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [25]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [26]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [27]:
# code
a.shape

(15,)

In [29]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [31]:
np.expand_dims(a,axis=1).shape

(15, 1)

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [33]:
a

array([18, 86, 27, 73, 61, 40, 21, 36, 84, 43, 58,  3, 94, 52, 47],
      dtype=int32)

In [34]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 1,  3,  4,  8, 10, 12, 13]),)

In [35]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([18,  0, 27,  0,  0, 40, 21, 36,  0, 43,  0,  3,  0,  0, 47],
      dtype=int32)

In [ ]:
np.where(a%2 == 0,0,a)

array([11, 53,  0,  0,  0, 37,  0,  0,  5,  0,  0,  9,  0,  0, 21])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [36]:
# code
a

array([18, 86, 27, 73, 61, 40, 21, 36, 84, 43, 58,  3, 94, 52, 47],
      dtype=int32)

In [37]:
np.argmax(a)

np.int64(12)

In [38]:
b

array([[39, 73, 62, 66],
       [47, 58, 83, 62],
       [94, 77, 34, 69],
       [54, 36,  2, 95],
       [68,  9, 55, 80],
       [55, 14, 17, 96]], dtype=int32)

In [39]:
np.argmax(b,axis=0)

array([2, 2, 1, 5])

In [40]:
np.argmax(b,axis=1)

array([1, 2, 0, 3, 3, 3])

In [41]:
# np.argmin
np.argmin(a)

np.int64(11)

In [42]:
a

array([18, 86, 27, 73, 61, 40, 21, 36, 84, 43, 58,  3, 94, 52, 47],
      dtype=int32)

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [43]:
a

array([18, 86, 27, 73, 61, 40, 21, 36, 84, 43, 58,  3, 94, 52, 47],
      dtype=int32)

In [44]:
np.cumsum(a)

array([ 18, 104, 131, 204, 265, 305, 326, 362, 446, 489, 547, 550, 644,
       696, 743])

In [45]:
b

array([[39, 73, 62, 66],
       [47, 58, 83, 62],
       [94, 77, 34, 69],
       [54, 36,  2, 95],
       [68,  9, 55, 80],
       [55, 14, 17, 96]], dtype=int32)

In [47]:
np.cumsum(b,axis=0)

array([[ 39,  73,  62,  66],
       [ 86, 131, 145, 128],
       [180, 208, 179, 197],
       [234, 244, 181, 292],
       [302, 253, 236, 372],
       [357, 267, 253, 468]])

In [49]:
np.cumsum(b)

array([  39,  112,  174,  240,  287,  345,  428,  490,  584,  661,  695,
        764,  818,  854,  856,  951, 1019, 1028, 1083, 1163, 1218, 1232,
       1249, 1345])

In [50]:
a

array([18, 86, 27, 73, 61, 40, 21, 36, 84, 43, 58,  3, 94, 52, 47],
      dtype=int32)

In [51]:
# np.cumprod
np.cumprod(a)

array([                 18,                1548,               41796,
                   3051108,           186117588,          7444703520,
              156338773920,       5628195861120,     472768452334080,
         20329043450365440, 1179084520121195520, 3537253560363586560,
        460441347405207552, 5496205991361241088,   67264562044608512])

In [ ]:
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [54]:
np.sort(a)

array([ 3, 18, 21, 27, 36, 40, 43, 47, 52, 58, 61, 73, 84, 86, 94],
      dtype=int32)

In [55]:
np.percentile(a,80)

np.float64(75.20000000000002)

In [ ]:
np.median(a)

37.0

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [ ]:
ap=[1,1,1,5,5,6,7,8,8,9,5,5,1,2]

In [56]:
# code
a

array([18, 86, 27, 73, 61, 40, 21, 36, 84, 43, 58,  3, 94, 52, 47],
      dtype=int32)

In [59]:
np.histogram(a,bins=[0,20,40,60,80,100])

(array([2, 3, 5, 2, 3]), array([  0,  20,  40,  60,  80, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [ ]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [60]:
# code
a


array([18, 86, 27, 73, 61, 40, 21, 36, 84, 43, 58,  3, 94, 52, 47],
      dtype=int32)

In [63]:
items = [10,20,30,40,36,50,60,70,80,90,100]

a[np.isin(a,items)]

array([40, 36], dtype=int32)

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [64]:

# code
a

array([18, 86, 27, 73, 61, 40, 21, 36, 84, 43, 58,  3, 94, 52, 47],
      dtype=int32)

In [65]:
np.flip(a)

array([47, 52, 94,  3, 58, 43, 84, 36, 21, 40, 61, 73, 27, 86, 18],
      dtype=int32)

In [66]:
b

array([[39, 73, 62, 66],
       [47, 58, 83, 62],
       [94, 77, 34, 69],
       [54, 36,  2, 95],
       [68,  9, 55, 80],
       [55, 14, 17, 96]], dtype=int32)

In [68]:
np.flip(b,axis=0)

array([[55, 14, 17, 96],
       [68,  9, 55, 80],
       [54, 36,  2, 95],
       [94, 77, 34, 69],
       [47, 58, 83, 62],
       [39, 73, 62, 66]], dtype=int32)

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [76]:
# code
a

array([-44,   1, -55,   3,   4])

In [75]:
a = np.arange(5)
np.put(a, [0, 2], [-44, -55])
a


array([-44,   1, -55,   3,   4])

In [77]:
a = np.random.randint(1,100,15)
a

array([ 2, 89, 13, 38, 87, 59, 30, 92, 74, 11, 18, 89, 72, 30, 94],
      dtype=int32)

In [81]:
np.put(a,[0,1],[10,30])
a

array([10, 30, 13, 38, 87, 59, 30, 92, 74, 11, 18, 89, 72, 30, 94],
      dtype=int32)

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [82]:
# code
a

array([10, 30, 13, 38, 87, 59, 30, 92, 74, 11, 18, 89, 72, 30, 94],
      dtype=int32)

In [83]:
np.delete(a,[0,2,4])

array([30, 38, 59, 30, 92, 74, 11, 18, 89, 72, 30, 94], dtype=int32)

In [84]:
a

array([10, 30, 13, 38, 87, 59, 30, 92, 74, 11, 18, 89, 72, 30, 94],
      dtype=int32)

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [85]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
np.intersect1d(m,n)

array([3, 4, 5])

In [87]:
np.setdiff1d(m,n)

array([1, 2])

In [88]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [90]:
m[np.in1d(m,6)]

C:\Users\tops\AppData\Local\Temp\ipykernel_8984\1841458627.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  m[np.in1d(m,6)]


array([], dtype=int64)

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [91]:
# code
a

array([10, 30, 13, 38, 87, 59, 30, 92, 74, 11, 18, 89, 72, 30, 94],
      dtype=int32)

In [92]:
np.clip(a,a_min=25,a_max=75)

array([25, 30, 25, 38, 75, 59, 30, 75, 74, 25, 25, 75, 72, 30, 75],
      dtype=int32)

In [ ]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5